INSERT INTO PERSON (ID, FIRSTNAME, MIDDLENAME, LASTNAME, EMAIL, PHONE) VALUES (1, 'John', null, 'Doe', 'john.doe@sixturtle.com', '(512) 456-1001');
INSERT INTO PERSON (ID, FIRSTNAME, MIDDLENAME, LASTNAME, EMAIL, PHONE) VALUES (2, 'Mary', null, 'Doe', 'mary.doe@sixturtle.com', '(512) 456-1002');
ALTER SEQUENCE hibernate_sequence RESTART WITH 3;